export enum IconSetEnum {
  dropdownBold = 'dropdownBold',
  calender = 'calender',
  Cancel = 'Cancel',
  categoryMenu = 'categoryMenu',
  checkCircle = 'checkCircle',
  circleMenu = 'circleMenu',
  event = 'event',
  faq = 'faq',
  fileClipped = 'fileClipped',
  folder = 'folder',
  folderBunch = 'folderBunch',
  lock = 'lock',
  menu = 'menu',
  optionMenu = 'optionMenu',
  rightArrow = 'rightArrow',
  rightArrowMedium = 'rightArrowMedium',
  rightDirection = 'rightDirection',
  search = 'search',
  settings = 'settings',
  userCore = 'userCore',
  usermedium = 'usermedium',
}